---
host_domain: "jupyter.{{ cluster_name }}.dev-jupyter.stfc.ac.uk"
longhorn_ip: "130.246.83.115"
staging_cert: true

use_traefik: true

admin_names:
  -
  -
# password must bet atleast 32 characters long to deploy correctly
admin_password:
number_of_users:
username:
# password must bet atleast 32 characters long to deploy correctly
user_password:
profiles:
  - profile1:
    display_name: "Default environment"
    description: "This is a simple default environment"
    default: true
    ram: "5G"
    image: jupyter/minimal-notebook
    node_groups: []
    gpu_required: false
    gpu_display_drivers: false
    # Please remove '-'s if no commands required
    commands:
      -
      -

# Set number of users per GPU
# Available profiles: users2, users3, users4
# users2 = 2 users per gpu, users3 = 3 users per gpu, etc.
# Example
#
# gpu_profiles:
#   - node_group: gpu
#     profile: users2
#   - node_group: gpu2
#     profile: users3

manila:
  required: false
  mount_path: "/home/jovyan/manila"
  share_name: new-cephfs-share-pvc

iris_iam:
  required: false
  client_id:
  client_secret:
  admin_groups:
    -
    -
  allowed_groups:
    -
    -
