---
host_domain: "training.jupyter.stfc.ac.uk"
ip_address: "130.246.213.196"
longhorn_ip: "130.246.213.143"
staging_cert: false

admin_names:
  -
  -
# password must bet atleast 32 characters long to deploy correctly
admin_password:
number_of_users:
username:
# password must bet atleast 32 characters long to deploy correctly
user_password:
profiles:
  - profile1:
    display_name: "Default environment"
    description: "This is a simple default environment"
    default: true
    # ram:
    image: jupyter/minimal-notebook
    node_groups: []
    gpu_required: false
    gpu_display_drivers: false
    # Please remove '-'s if no commands required
    commands:
      -
      -

# Uncomment to set users per gpu
# gpu_profiles:
#   - profile: users2
#     node_group: gpu
#   - profile: users3
#     node_group: gpu2

manila:
  required: false
  mount_path: "/home/jovyan/manila"
  share_name: new-cephfs-share-pvc

iris_iam:
  required: false
  client_id:
  client_secret:
  admin_groups:
    -
    -
  allowed_groups:
    -
    -
