---
# Todo: Delete once Traefik is enabled on prod, or otherwise change the domain
host_domain: "training.jupyter.stfc.ac.uk"
ip_address: "130.246.213.196"
longhorn_ip: "130.246.213.143"
staging_cert: false

use_traefik: false

profiles:
  - profile1:
    display_name: "Default environment"
    description: "This is a simple default environment"
    default: true
    # ram:
    image: jupyter/minimal-notebook
    node_groups: []
    gpu_required: false
    gpu_display_drivers: false
    # Please remove '-'s if no commands required
    commands:
      -
      -

# Uncomment to set users per gpu
# gpu_profiles:
#   - profile: users2
#     node_group: gpu
#   - profile: users3
#     node_group: gpu2

manila:
  required: false
  mount_path: "/home/jovyan/manila"
  share_name: new-cephfs-share-pvc

# One of ["shared_password", "iris_iam" or "keycloak"]
authentication_method: "shared_password"

shared_password:
  # Will be proceeded with "admin-"
  admin_names:
    -
  # password must bet atleast 32 characters long to deploy correctly
  admin_password:
  number_of_users:
  username_prefix: user-
  # password must bet atleast 32 characters long to deploy correctly
  user_password:
keycloak:
  # Use traefik, or the loadbalancer IP's domain name
  domain:
  url:
  # Not used for Traefik
  loadBalancerIP:
  # Details for the default keycloak administrator
  system_admin_username:
  system_admin_password:
  # Realm & OIDC Client details
  realm: "jupyter"
  client_id: "jupyterhub-client"

  # A secret token for OIDC i.e. `openssl rand -hex 32`
  client_secret:
  claim_groups_key: "groups"

  # Groups configuration
  user_group: jupyter-user
  admin_group: jupyter-admin

  # Provisioning settings for user creation
  # Will be proceeded with "admin-"
  admin_names:
    -
  number_of_users: 3

  username_prefix: user-

  # Default temporary passwords. Users will be prompted to change them after first login
  default_user_password:
  default_admin_password:
iris_iam:
  client_id:
  client_secret:
  admin_groups:
    -
    -
  allowed_groups:
    -
    -
