---
- name: Check authentication method
  ansible.builtin.assert:
    that: "authentication_method in ['shared_password', 'iris_iam', 'keycloak']"

- name: Verify shared password settings
  when: authentication_method == "shared_password"
  block:
    - name: Check user password meets requirements
      ansible.builtin.fail:
        msg: "User password must be at least 32 characters"
      when: shared_password.user_password | length < 32

    - name: Check admin password meets requirements
      ansible.builtin.fail:
        msg: "Admin password must be at least 32 characters"
      when: shared_password.admin_password | length < 32

# TODO: Enable ListenerSet
# - name: Deploy listenerset
#   kubernetes.core.k8s:
#     kubeconfig: "{{ kubeconfig_path }}"
#     state: present
#     resource_definition:
#       apiVersion: gateway.networking.k8s.io/v1
#       kind: ListenerSet
#       metadata:
#         name: jupyterhub
#         namespace: jupyterhub
#         annotations:
#           cert-manager.io/cluster-issuer: letsencrypt-http01
#           acme.cert-manager.io/http01-parentreffallback: "true"
#       spec:
#         parentRef:
#           name: traefik-gateway
#           namespace: traefik
#         listeners:
#           - name: websecure
#             hostname: "{{ host_domain }}"
#             port: 8443
#             protocol: HTTPS
#             tls:
#               mode: Terminate
#               certificateRefs:
#                 - name: jupyterhub-tls

- name: Install pre-set version of hub. This may take up to 25m to pull various images...
  kubernetes.core.helm:
    chart_ref: "{{ jhub_chart_ref }}"
    chart_repo_url: "{{ jhub_repo_url }}"
    release_name: "{{ jhub_deployed_name }}"
    chart_version: "{{ jhub_version }}"
    release_namespace: "{{ jhub_namespace }}"
    create_namespace: true
    kubeconfig: "{{ kubeconfig_path }}"
    wait: true
    release_values: "{{ jupyterhub_config_values }}"
    timeout: "25m"
