---
- name: Deploy JupyterHub
  hosts: bootstrap # Kubectl is configured from this machine
  gather_facts: true
  environment:
    PATH: "{{ ansible_env.PATH }}"
  vars_files:
    - group_vars/all.yaml
    - "group_vars/{{ env }}.yaml"
  roles:
    - check_cluster
    - deploy_longhorn
    - role: deploy_keycloak
      when: authentication_method == "keycloak"
    - deploy_jupyterhub
    - role: gpu_sharing
      when: gpu_profiles is defined
    - role: restart_autohttps
      when: not use_traefik
    - role: change_owner_of_manila_pod
      when: manila.required
