---
- name: Destroy JupyterHub
  hosts: bootstrap # Kubectl is configured from this machine
  gather_facts: true
  environment:
    PATH: "{{ ansible_env.PATH }}"
  vars_files:
    - group_vars/all.yaml
    - "group_vars/{{ env }}.yaml"
  roles:
    - check_cluster
    - destroy_jupyterhub
    - destroy_keycloak
    - destroy_longhorn
