apiVersion: v1
kind: PersistentVolume
metadata:
  name: training-materials
  namespace: jhub
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 10.0.0.253
    path: "/var/training-materials"
