- name: Create Longhorn namespace
  kubernetes.core.k8s:
    name: longhorn-system
    kind: Namespace
    state: present

- name: Download Longhorn repos
  ansible.builtin.git:
    repo: "{{ longhorn_repo_name }}"
    dest: "/tmp/longhorn"
    version: "{{ longhorn_version }}"
    update: true # Automatically pull bug-fixes in

- name: Install Longhorn prerequisites
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
    namespace: longhorn-system
  with_items:
    - "/tmp/longhorn/deploy/prerequisite/longhorn-iscsi-installation.yaml"
    - "/tmp/longhorn/deploy/prerequisite/longhorn-nfs-installation.yaml"

- name: Install Longhorn helm repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Install Longhorn
  kubernetes.core.helm:
    chart_ref: longhorn/longhorn
    name: longhorn
    release_namespace: longhorn-system
    update_repo_cache: yes
    release_values:
      taintToleration: "nvidia.com/gpu:NoSchedule"
      service:
        ui:
          type: LoadBalancer
      persistence:
        defaultClassReplicaCount: 3
        defaultDataLocality: disabled

- name: Create the working namespace
  kubernetes.core.k8s:
    name: "{{ hub_namespace }}"
    kind: Namespace
    state: present

- name: Create NFS yaml files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {src: "{{ role_path }}/templates/nfs-pvc.j2", dest: "/tmp/nfs-pvc.yaml"}
    - {src: "{{ role_path }}/templates/nfs-pv.j2", dest: "/tmp/nfs-pv.yaml"}

- name: Enable the training materials NFS share
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
    namespace: "{{ hub_namespace }}"
  with_items:
    - "/tmp/nfs-pvc.yaml"
    - "/tmp/nfs-pv.yaml"

- name: Install hub helm repo
  kubernetes.core.helm_repository:
    name: "{{ hub_repo_name }}"
    repo_url: "{{ hub_repo_url }}"

- name: Install pre-set version of hub. This may take up to 25m to pull various images...
  kubernetes.core.helm:
    chart_ref: "{{ hub_chart_ref }}"
    update_repo_cache: yes
    # Pulled from default
    name: "{{ hub_deployed_name }}"
    chart_version: "{{ hub_version }}"
    release_namespace: "{{ hub_namespace }}"
    values_files:
      - "{{ role_path }}/{{ hub_config_file }}"
    timeout: "25m"
