apiVersion: v1
kind: PersistentVolume
metadata:
  name: training-materials
  namespace: jupyterhub
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 172.16.101.240
    path: "/var/training-materials"
