apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-materials
  namespace: jupyterhub
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
