- name: Download Openstack Controller Repo
  ansible.builtin.git:
    repo: "https://github.com/kubernetes/cloud-provider-openstack.git"
    dest: "/tmp/cloud-provider-openstack"
    version: "release-1.24"
    update: true # Automatically pull bug-fixes in

- name: Install Openstack Controller Manager
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
    namespace: kube-system
  with_items:
    - "/tmp/cloud-provider-openstack/manifests/controller-manager/cloud-controller-manager-roles.yaml"
    - "/tmp/cloud-provider-openstack/manifests/controller-manager/cloud-controller-manager-role-bindings.yaml"
    - "/tmp/cloud-provider-openstack/manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml"

- name: Create Longhorn namespace
  kubernetes.core.k8s:
    name: longhorn-system
    kind: Namespace
    state: present

- name: Download Longhorn repo
  ansible.builtin.git:
    repo: "https://github.com/longhorn/longhorn.git"
    dest: "/tmp/longhorn"
    version: "v1.2.5"
    update: true # Automatically pull bug-fixes in

- name: Install Longhorn prerequisites
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
    namespace: longhorn-system
  with_items:
    - "/tmp/longhorn/deploy/prerequisite/longhorn-iscsi-installation.yaml"
    - "/tmp/longhorn/deploy/prerequisite/longhorn-nfs-installation.yaml"

- name: Install Longhorn helm repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Install Longhorn
  kubernetes.core.helm:
    chart_ref: longhorn/longhorn
    name: longhorn
    release_namespace: longhorn-system
    update_repo_cache: yes
    release_values:
      taintToleration: "nvidia.com/gpu:NoSchedule"
      service:
        ui:
          type: LoadBalancer
      persistence:
        defaultClassReplicaCount: 3
        defaultDataLocality: disabled

- name: Create the working namespace
  kubernetes.core.k8s:
    name: "{{ jhub_namespace }}"
    kind: Namespace
    state: present

- name: Enable the training materials NFS share
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
    namespace: "{{ jhub_namespace }}"
  with_items:
    - "{{ role_path }}/files/nfs-pvc.yaml"
    - "{{ role_path }}/files/nfs-pv.yaml"

- name: Install jhub helm repo
  kubernetes.core.helm_repository:
    name: jupyterhub
    repo_url: https://jupyterhub.github.io/helm-chart/

- name: Install pre-set version of Jhub. This may take up to 25m to pull various images...
  kubernetes.core.helm:
    chart_ref: jupyterhub/jupyterhub
    create_namespace: yes
    update_repo_cache: yes
    # Pulled from default
    name: "{{ jhub_deployed_name }}"
    chart_version: "{{ jhub_version }}"
    release_namespace: "{{ jhub_namespace }}"
    values_files:
      - "{{ role_path }}/files/{{ jhub_config_file }}"
    timeout: "25m"

- name: Create namespace for Nvidia components
  kubernetes.core.k8s:
    name: "{{ item }}"
    kind: Namespace
    state: present
  with_items:
    - gpu-operator

- name: Install Nvidia GPU Operator repo
  kubernetes.core.helm_repository:
    name: nvidia
    repo_url: https://nvidia.github.io/gpu-operator

- name: Install GPU Operator, pointing to own driver
  kubernetes.core.helm:
    chart_ref: nvidia/gpu-operator
    update_repo_cache: yes
    chart_version: "1.11.1"
    name: gpu-operator
    release_namespace: gpu-operator
    release_values:
      driver:
        repository: "nvcr.io/nvidia"
        image: "driver"
        version: "{{ NVIDIA_DRIVER_VERSION }}"
