- name: Test K8s service is contactable. If this fails check $KUBECONFIG is set.
  kubernetes.core.k8s_cluster_info:

- name: Enable PV Claims on Cinder
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/files/{{ storage_class_file }}"

- name: Create the working namespace
  kubernetes.core.k8s:
    name: "{{ jhub_namespace }}"
    kind: Namespace
    state: present

- name: Install jhub helm repo
  kubernetes.core.helm_repository:
    name: jupyterhub
    repo_url: https://jupyterhub.github.io/helm-chart/

- name: Install pre-set version of Jhub (Plugin Mode)
  kubernetes.core.helm:
    chart_ref: jupyterhub/jupyterhub
    create_namespace: yes
    update_repo_cache: yes
    # Pulled from default
    name: "{{ jhub_deployed_name }}"
    chart_version: "{{ jhub_version }}"
    release_namespace: "{{ jhub_namespace }}"
    values_files:
      - "{{ role_path }}/files/{{ jhub_config_file }}"
  when: jupyter_large_image_install_mode == false

- name: Install pre-set version of Jhub (Command Mode)
  command: helm install {{ jhub_deployed_name }} jupyterhub/jupyterhub -f "{{ role_path }}/files/{{ jhub_config_file }}" --timeout "2h" --create-namespace --namespace {{ jhub_namespace }} --version "{{ jhub_version }}"
  when: jupyter_large_image_install_mode == true

- name: Create namespace for Nvidia components
  kubernetes.core.k8s:
    name: "{{ item }}"
    kind: Namespace
    state: present
  with_items:
    - gpu-operator
    - gpu-operator-resources

- name: Create the priorityClassName for nvidiaComponent
  # The default will set gpu daemonset and operator at system-node-critical 
  # which can't start outside of kube-system namespace in earlier version of k8s (<1.17)
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/files/nvidia-priority-class.yaml"

- name: Install Nvidia GPU Operator repo
  kubernetes.core.helm_repository:
    name: nvidia
    repo_url: https://nvidia.github.io/gpu-operator

- name: Install GPU Operator, pointing to own driver
  kubernetes.core.helm:
    chart_ref: nvidia/gpu-operator
    update_repo_cache: yes
    # Pulled from default
    name: gpu-operator
    release_namespace: gpu-operator
    release_values:
      daemonsets:
        priorityClassName: nvidia-priority-class
      operator:
        priorityClassName: nvidia-priority-class
      driver:
        repository: "harbor.stfc.ac.uk/stfc-cloud-private"
        image: "nvidia_driver"
        version: "{{ NVIDIA_DRIVER_VERSION }}"