---
chown_job_spec:
  apiVersion: batch/v1
  kind: Job
  metadata:
    name: busybox-chown
    namespace: openstack-system
  spec:
    backoffLimit: 2
    template:
      spec:
        restartPolicy: Never
        containers:
          - name: busybox
            image: busybox
            command: ["sh", "-c", "chown -R 1000:100 {{ manila.mount_path }}"]
            securityContext:
              runAsUser: 0
              capabilities:
                add: ["CHOWN"]
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: "50m"
                memory: "64Mi"
              limits:
                cpu: "200m"
                memory: "128Mi"
            volumeMounts:
              - name: "{{ manila.share_name }}"
                mountPath: "{{ manila.mount_path }}"
        volumes:
          - name: "{{ manila.share_name }}"
            persistentVolumeClaim:
              claimName: "{{ manila.share_name }}"
              readOnly: false
