apiVersion: v1
kind: PersistentVolume
metadata:
  name: training-materials
  namespace: jupyterhub
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  nfs:
    server: <NFS Server IP>
    path: "/var/training-materials"
