---
- name: Apply init job
  kubernetes.core.k8s:
    state: present
    definition: "{{ chown_job_spec }}"
    kubeconfig: "{{ kubeconfig_path }}"

- name: Wait for job completion
  kubernetes.core.k8s_info:
    kind: Job
    namespace: openstack-system
    name: busybox-chown
    kubeconfig: "{{ kubeconfig_path }}"
  register: job_status
  until: >
    job_status.resources | length > 0 and (
      (job_status.resources[0].status.succeeded | default(0)) >= 1
      or
      (job_status.resources[0].status.failed | default(0)) >= 1
    )
  retries: 30
  delay: 10

- name: Fail if job failed
  ansible.builtin.fail:
    msg: "Job failed"
  when: job_status.resources[0].status.failed | default(0) > 0
