# Advanced settings which are magnum specific

docker_volume_size_gb: 10
# Magnum deploys 1.0 by default, we need 1.19+ to be Node Group aware
cluster_autoscaler_version: "v1.19.1"
# Highest K8s version supported by Victoria and below
kube_tag: "v1.18.20"
# Because the official mirror (which we mirror from) uses vx.y.z instead of x.y.z that coreos uses
etcd_tag: "v3.5.4"

# Kubernetes specific
# We need to enable the priority plugin manually, the list of default plugins + 'Priority' is from:
# https://opendev.org/openstack/magnum/src/branch/stable/ussuri/magnum/drivers/k8s_fedora_coreos_v1/templates/kubecluster.yaml
admission_plugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,Priority"
# Is this best practice, no. But until https://github.com/NVIDIA/gpu-operator/issues/26
# is merged we have to use their hardcoded taint, despite the fact only the driver
# should be using this
gpu_taint: "nvidia.com/gpu=present:NoSchedule"
kubectl_port: 6443
