- hosts: localhost # Kubectl is configured from this machine
  roles:
    - deploy_jhub
    - deploy_prometheus_stack
  vars:
    # Persistant Volume Claim
    ## config file for storage class (Check with your cloud provider)  
    ## you have to change the name of storage class in config.yaml in /role/deplyo_jhub/files/{{ your_jhub_config_file }}
    #
    # singleuser: 
    #   storage: 
    #     dynamic: 
    #       Storage Class: {{ name }}
    storage_class_file: "cinder-kube-storage.yaml"
    # Timeout can occur for larger image size
    jupyter_large_image_install_mode: true

    # Helm name of the service
    jhub_deployed_name: jupyterhub
    # K8s namespace
    jhub_namespace: jupyterhub
    # Helm chart version for Jhub (newer version may require newer kubernetes version >=1.17)
    jhub_version: "1.2.0"
    # config file for JupyterHub helm chart (in "/roles/deploy_jhub/files")
    jhub_config_file: "config.yaml"

    # Helm name of the prometheus service
    prometheus_deployed_name: prometheus
    # K8s namespace
    prometheus_namespace: prometheus
    # Grafana dashboard admin password
    grafana_password: "temp_password"

    # Even if you don't use GPUs we deploy the Nvidia GPU operator
    # for simplicity (otherwise we need another var to enable GPU support across notebooks).

    # This version needs have been built by running playbooks/build_gpu_driver.yml beforehand
    NVIDIA_DRIVER_VERSION: 460.32.03
    #NVIDIA_DRIVER_VERSION: 470.82.01
