- hosts: localhost # Kubectl is configured from this machine
  roles:
    - deploy_hub
    # - deploy_prometheus_stack
  vars:
    # Even if you don't use GPUs we deploy the Nvidia GPU operator
    # for simplicity (otherwise we need another var to enable GPU support across notebooks).
    # This version will be pulled from the Nvidia NGC catalogue
    NVIDIA_DRIVER_VERSION: 515.48.07

    # Helm chart version for Jhub (newer version may require newer kubernetes version >=1.17)
    hub_version: "1.2.0"
    # Name of JupyterHub cluster used in load balancer names
    hub_cluster_name: jupyterhub_cluster
    # K8s namespace
    hub_namespace: jupyterhub
    # Helm name of the service
    hub_deployed_name: jupyterhub
    # config file for JupyterHub helm chart (in "/roles/deploy_jhub/files")
    hub_config_file: ../deploy_jhub/files/config.yaml
    # Name of repository
    hub_repo_name: jupyterhub
    # Helm chart repository URL for JupyterHub
    hub_repo_url: https://jupyterhub.github.io/helm-chart/
    # Chart reference for JupyterHub
    hub_chart_ref: jupyterhub/jupyterhub

    # Helm name of the prometheus service
    prometheus_deployed_name: prometheus
    # K8s namespace
    prometheus_namespace: prometheus
    # Grafana dashboard admin password
    grafana_password: "temp_password"
